substitutions:
  device_name: alarm_8266
  device_friendly_name: Allarme

packages:
  base: !include common/.base.yaml
  board: !include common/.board.amica_nodemcuv2.yaml
  floor: !include common/.downstairs.yaml

font:
    # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto_20
    size: 20

sx1509:
  - id: sx1509_hub1
    address: 0x3E
    # If you need a keypad
    keypad:
      key_rows: 4
      key_columns: 4
      sleep_time: 256
      scan_time: 2
      debounce_time: 1
      on_key: 
        then:
          - logger.log: "Called with key ${x}"

key_collector:
  - id: pincode_reader
    min_length: 4
    max_length: 4
    end_keys: "#"
    end_key_required: true
    back_keys: "*"
    clear_keys: "C"
    allowed_keys: "0123456789"
    timeout: 5s
    on_progress:
      - logger.log:
          format: "input progress: '%s', started by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)" ]
    on_result:
      - logger.log:
          format: "input result: '%s', started by '%c', ended by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)", "(end == 0 ? '~' : end)" ]
    on_timeout:
      - logger.log:
          format: "input timeout: '%s', started by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)" ]

i2c:
  sda: D1
  scl: D2

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    reset_pin: D0
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(roboto_20), "Hello World!");