substitutions:
  device_name: dehumidifier
  device_friendly_name: Deumidificatore

packages:
  base: !include common/.base.yaml
  board: !include common/.board.esp32dev.yaml
  upstairs: !include common/.upstairs.yaml

external_components:
  - source:
      type: local
      path: my_components
    components: [fan_controller]

select:
  - platform: template
    id: fan_mode
    name: Modalità
    entity_category: CONFIG
    options:
      - "OFF"
      - "SMART"
      - "CONTINUOUS"
      - "DRYER"
      - "OTHER"
    set_action:
      then:
        - logger.log:
            format: "Chosen option: %s"
            args: ["x.c_str()"]

sensor:
  - platform: template
    id: fan_speed_sensor
    name: "Fan Speed Sensor"
    update_interval: 10s
    lambda: |-
      if (id(led_7).state && id(led_6).state) {
        return 3;  // Max speed
      } else if (id(led_7).state) {
        return 1;  // Slow speed
      } else if (id(led_6).state) {
        return 2;  // Medium speed
      } else {
        return NAN;  // Off
      }

script:
  - id: update_mode
    mode: restart
    then:
      - lambda: |-
          ESP_LOGD("script.update_mode", "Starting (states: %i, %i, %i) [current: %s]", id(led_2).state, id(led_3).state, id(led_4).state, id(fan_mode).state);
          auto call = id(fan_mode).make_call();

          if (id(led_2).state) {
            call.set_option("SMART");
          } else if (id(led_3).state) {
            call.set_option("CONTINUOUS");
          } else if (id(led_4).state) {
            call.set_option("DRYER");
          } else if (id(led_1).state) {
            call.set_option("OTHER"); // Need to check manual for description of this state
          } else {
            call.set_option("OFF");
          }

          call.perform();
          ESP_LOGD("script.update_fan_mode", "Done, set to %s", id(fan_mode).state);

# Emulated buttons
button:
  - platform: output
    id: btn_power
    name: Toggle power
    output: btn_1
    duration: 250ms
  - platform: output
    id: btn_mode
    name: Cycle Mode
    output: btn_2
    duration: 250ms
  - platform: output
    id: btn_speed
    name: Cycle Fan speed
    output: btn_3
    duration: 250ms

# Raw optocouplers: outputs
output:
  - platform: gpio
    id: btn_1
    pin: GPIO32
  - platform: gpio
    id: btn_2
    pin: GPIO25
  - platform: gpio
    id: btn_3
    pin: GPIO33

# Raw optocouplers: inputs
binary_sensor:
  - platform: gpio
    id: led_1
    # name: "LED - ON"
    pin:
      number: GPIO16
      inverted: true
      mode: INPUT_PULLUP
    on_state: # Only process when turning off, avoids concurrency
      then:
        - lambda: |-
            id(fan_ctrl).update_from_leds();
  - platform: gpio
    id: led_2
    name: "LED - Mode: Smart"
    pin:
      number: GPIO17
      inverted: true
      mode: INPUT_PULLUP
    on_state: 
      then:
        - script.execute: update_mode
  - platform: gpio
    id: led_3
    name: "LED - Mode: Continuous"
    pin:
      number: GPIO18
      inverted: true
      mode: INPUT_PULLUP
    on_state: 
      then:
        - script.execute: update_mode
  - platform: gpio
    id: led_4
    name: "LED - Mode: Dryer"
    pin:
      number: GPIO19
      inverted: true
      mode: INPUT_PULLUP
    on_state: 
      then:
        - script.execute: update_mode
  - platform: gpio
    id: led_5
    name: "Tank full"
    # icon: mdi:water-alert
    device_class: moisture
    pin:
      number: GPIO21
      inverted: true
      mode: INPUT_PULLUP
  - platform: gpio
    id: led_6
    name: "LED - Fan Speed 2"
    pin:
      number: GPIO22
      inverted: true
      mode: INPUT_PULLUP
    on_state: # Only process when turning on, avoids concurrency
      then:
        - lambda: |-
            id(fan_ctrl).update_from_leds();
  - platform: gpio
    id: led_7
    name: "LED - Fan Speed 1"
    pin:
      number: GPIO23
      inverted: true
      mode: INPUT_PULLUP
    on_state: # Only process when turning on, avoids concurrency
      then:
        - lambda: |-
            id(fan_ctrl).update_from_leds();


# Custom fan platform
fan_controller:
  name: Ventola
  id: fan_ctrl
  power_output: btn_1
  speed_output: btn_3
  low_led: led_7
  high_led: led_6
