substitutions:
  device_name: modbus-test
  device_friendly_name: Modbus Test

packages:
  base: !include common/.base.yaml
  board: !include common/.board.esp32dev.yaml
  floor: !include common/.downstairs.yaml

uart:
  - id: uart_modbus_client
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 115200
    debug:
      direction: BOTH
      dummy_receiver: false
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);


modbus:
  - id: modbus_client
    uart_id: uart_modbus_client

modbus_controller:
  - id: modbus_test
    address: 0x4   ## address of the Modbus slave device on the bus
    modbus_id: modbus_client
    setup_priority: -10

sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_test
    name: "Random number"
    register_type: holding
    address: 0x0002   ## address of the register inside the Modbus slave device
    value_type: S_DWORD_R
    accuracy_decimals: 1
    lambda: |-
        ESP_LOGI("","Lambda incoming value=%f - data array size is %d",x,data.size());
        ESP_LOGI("","Sensor properties: adress = 0x%X, offset = 0x%X value type=%d",item->start_address,item->offset,item->sensor_value_type);
        int i=0 ;
        for (auto val : data) {
          ESP_LOGI("","data[%d]=0x%02X (%d)",i,data[i],data[i]);
          i++;
        }
        return x ;

select:
  - id: change_baud_rate
    name: Baud rate
    platform: template
    options:
      - "2400"
      - "9600"
      - "38400"
      - "57600"
      - "115200"
      - "256000"
      - "512000"
      - "921600"
    initial_option: "115200"
    optimistic: true
    restore_value: True
    internal: false
    entity_category: config
    icon: mdi:swap-horizontal
    set_action:
      - lambda: |-
          id(uart_modbus_client).flush();
          uint32_t new_baud_rate = stoi(x);
          ESP_LOGD("change_baud_rate", "Changing baud rate from %i to %i",id(uart_modbus_client).get_baud_rate(),
                    new_baud_rate);
          if (id(uart_modbus_client).get_baud_rate() != new_baud_rate) {
            id(uart_modbus_client).set_baud_rate(new_baud_rate);
            id(uart_modbus_client).load_settings();
          }