substitutions:
  device_name: studio-giorgio
  device_friendly_name: Studio Giorgio

packages:
  base: !include common/.base.yaml
  board: !include common/.board.amica_nodemcuv2.yaml
  floor: !include common/.downstairs.yaml

sensor:
  - platform: dht
    pin:
      number: D8
      mode:
        input: true
        pullup: true
    temperature:
      name: "Temperatura"
      id: test_temperature
    humidity:
      name: "Umidità"
      id: test_humidity
    update_interval: 60s