substitutions:
  device_name: sonoff-s60
  device_friendly_name: Sonoff S60

packages:
  base: !include common/.base.sonoff-s60.yaml
  floor: !include common/.downstairs.yaml

switch:
- id: !extend relay
  device_class: outlet
  icon: mdi:radiator