substitutions:
  device_name: sonoff-s20
  device_friendly_name: Sonoff S20

packages:
  base: !include common/.base.sonoff-s20.yaml
  floor: !include common/.downstairs.yaml

switch:
- id: !extend relay
  device_class: outlet