packages:
  core: !include .base.core.yaml
  wifi: !include .wifi.yaml

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}

button:
  - platform: restart
    id: restart_device
    entity_category: config
    name: "Restart"
  - platform: safe_mode
    id: restart_device_safemode
    entity_category: config
    name: Restart (Safe Mode)
  # Deep sleep until reset, not very useful
  # - platform: shutdown
  #   name: Shutdown

text_sensor:
  - platform: version
    name: ESPHome Version
    entity_category: "diagnostic"
    # hide_timestamp: true

sensor:
  - platform: uptime
    type: timestamp
    name: Uptime
    entity_category: "diagnostic"

time:
  - platform: homeassistant
    timezone: Europe/Rome

binary_sensor:
  - platform: status
    name: Status
    entity_category: "diagnostic"