packages:
  base: !include .base.yaml
  chip: !include .chip.esp8266_generic.yaml

logger:
  # Disable UART logging (pins GPIO1/3 are used for button/led)
  baud_rate: 0

binary_sensor:
  - platform: gpio
    id: "button"
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    id: blue_led
    pin:
      number: GPIO13
      inverted: True
  - platform: gpio
    name: Relè
    pin: GPIO14
    id: relay
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led

# Use red LED for connectivity status indicator
light:
  - platform: status_led
    id: led
    name: Led
    pin:
      number: GPIO3
      inverted: True
    entity_category: diagnostic


sensor:
  - platform: hlw8012
    id: power_sensor
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    # Higher value gives lower watt readout
    current_resistor: ${current_res}
    # Lower value gives lower voltage readout
    voltage_divider: ${voltage_div}
    current:
      id: current
      name: Corrente
      accuracy_decimals: 2
    energy:
      id: energy
      name: Energia
    voltage:
      id: voltage
      name: Tensione
    power:
      id: power
      name: Potenza
    update_interval: 15s