esphome:
  # name_add_mac_suffix: true
  platformio_options:
    board_upload.maximum_size: 4194304

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf

wifi:
  enable_btm: true
  enable_rrm: true

light:
  - platform: status_led
    id: led
    name: Led
    pin:
      number: GPIO15
      inverted: True
    entity_category: diagnostic