# Material Design System for ESPHome LVGL
# Based on Material Design 3 principles with ESPHome substitutions and YAML anchors

substitutions:
  # Base Color Palette (Material Design 3)
  md_color_primary: 0x6750A4
  md_color_primary_container: 0xEADDFF
  md_color_on_primary: 0xFFFFFF
  md_color_on_primary_container: 0x21005D

  md_color_secondary: 0x625B71
  md_color_secondary_container: 0xE8DEF8
  md_color_on_secondary: 0xFFFFFF
  md_color_on_secondary_container: 0x1D192B

  md_color_tertiary: 0x7D5260
  md_color_tertiary_container: 0xFFD8E4
  md_color_on_tertiary: 0xFFFFFF
  md_color_on_tertiary_container: 0x31111D

  md_color_error: 0xBA1A1A
  md_color_error_container: 0xFFDAD6
  md_color_on_error: 0xFFFFFF
  md_color_on_error_container: 0x410002

  md_color_success: 0x1B5E20
  md_color_success_container: 0xC8E6C9
  md_color_on_success: 0xFFFFFF
  md_color_on_success_container: 0x0D2818

  md_color_warning: 0xFFCE22
  md_color_warning_container: 0xFFE0B2
  md_color_on_warning: 0xFFFFFF
  md_color_on_warning_container: 0x2E1100

  md_color_info: 0x1565C0
  md_color_info_container: 0xBBDEFB
  md_color_on_info: 0xFFFFFF
  md_color_on_info_container: 0x102A43

  md_color_surface: 0xFFFBFE
  md_color_surface_dim: 0xDED8E1
  md_color_surface_bright: 0xFFFBFE
  md_color_surface_container_lowest: 0xFFFFFF
  md_color_surface_container_low: 0xF7F2FA
  md_color_surface_container: 0xF1ECF4
  md_color_surface_container_high: 0xECE6F0
  md_color_surface_container_highest: 0xE6E0E9
  md_color_surface_variant: 0xE7E0EC
  md_color_on_surface: 0x1C1B1F
  md_color_on_surface_variant: 0x49454F

  md_color_outline: 0x79747E
  md_color_outline_variant: 0xCAC4D0
  md_color_inverse_surface: 0x313033
  md_color_inverse_on_surface: 0xF4EFF4
  md_color_inverse_primary: 0xD0BCFF

  # Shadow Colors
  md_color_shadow: 0x000000
  md_color_scrim: 0x000000

  # Typography Scale
  md_font_display_large: roboto_28
  md_font_display_medium: roboto_24
  md_font_display_small: roboto_22
  md_font_headline_large: roboto_20
  md_font_headline_medium: roboto_18
  md_font_headline_small: roboto_16
  md_font_title_large: roboto_16
  md_font_title_medium: roboto_14
  md_font_title_small: roboto_12
  md_font_body_large: roboto_14
  md_font_body_medium: roboto_12
  md_font_body_small: roboto_10
  md_font_label_large: roboto_12
  md_font_label_medium: roboto_10
  md_font_label_small: roboto_8

  # Elevation & Shadows
  md_elevation_1_shadow_width: 2
  md_elevation_1_shadow_opa: 12%
  md_elevation_2_shadow_width: 4
  md_elevation_2_shadow_opa: 16%
  md_elevation_3_shadow_width: 8
  md_elevation_3_shadow_opa: 20%
  md_elevation_4_shadow_width: 12
  md_elevation_4_shadow_opa: 24%
  md_elevation_5_shadow_width: 16
  md_elevation_5_shadow_opa: 28%

  # Corner Radius
  md_corner_extra_small: 4
  md_corner_small: 8
  md_corner_medium: 12
  md_corner_large: 16
  md_corner_extra_large: 28
  md_corner_full: 65535

  # Spacing
  md_space_none: 0
  md_space_extra_small: 4
  md_space_small: 8
  md_space_medium: 12
  md_space_large: 16
  md_space_extra_large: 24
  md_space_extra_extra_large: 32

  # # Base Style Definitions using YAML anchors
  # base_styles: &base_styles
  # Base Surface Style
  base_surface: &base_surface
    bg_color: ${md_color_surface}
    text_color: ${md_color_on_surface}
    border_width: ${md_space_none}
    radius: ${md_corner_medium}
    pad_all: ${md_space_medium}

  # Base Container Style
  base_container: &base_container
    <<: *base_surface
    bg_color: ${md_color_surface_container}

  # Base Elevation Styles
  elevation_1: &elevation_1
    shadow_width: ${md_elevation_1_shadow_width}
    shadow_color: ${md_color_shadow}
    shadow_opa: ${md_elevation_1_shadow_opa}
    shadow_ofs_y: 1

  elevation_2: &elevation_2
    shadow_width: ${md_elevation_2_shadow_width}
    shadow_color: ${md_color_shadow}
    shadow_opa: ${md_elevation_2_shadow_opa}
    shadow_ofs_y: 2

  elevation_3: &elevation_3
    shadow_width: ${md_elevation_3_shadow_width}
    shadow_color: ${md_color_shadow}
    shadow_opa: ${md_elevation_3_shadow_opa}
    shadow_ofs_y: 4

  elevation_4: &elevation_4
    shadow_width: ${md_elevation_4_shadow_width}
    shadow_color: ${md_color_shadow}
    shadow_opa: ${md_elevation_4_shadow_opa}
    shadow_ofs_y: 8

  elevation_5: &elevation_5
    shadow_width: ${md_elevation_5_shadow_width}
    shadow_color: ${md_color_shadow}
    shadow_opa: ${md_elevation_5_shadow_opa}
    shadow_ofs_y: 12

  # # Button Styles
  # button_styles: &button_styles
  # Base Button
  button_base: &button_base
    <<: *base_surface
    radius: ${md_corner_large}
    pad_left: ${md_space_extra_large}
    pad_right: ${md_space_extra_large}
    pad_top: ${md_space_medium}
    pad_bottom: ${md_space_medium}
    text_font: ${md_font_label_large}
    align: center

  # Primary Button (Filled)
  button_primary: &button_primary
    <<: [*button_base, *elevation_1]
    bg_color: ${md_color_primary}
    text_color: ${md_color_on_primary}

  # Secondary Button (Filled Tonal)
  button_secondary: &button_secondary
    <<: [*button_base, *elevation_1]
    bg_color: ${md_color_secondary_container}
    text_color: ${md_color_on_secondary_container}

  # Outline Button
  button_outline: &button_outline
    <<: *button_base
    bg_color: ${md_color_surface}
    text_color: ${md_color_primary}
    border_width: 1
    border_color: ${md_color_outline}

  # Text Button
  button_text: &button_text
    <<: *button_base
    bg_color: transparent
    text_color: ${md_color_primary}

  # FAB (Floating Action Button)
  button_fab: &button_fab
    <<: [*button_base, *elevation_3]
    bg_color: ${md_color_primary_container}
    text_color: ${md_color_on_primary_container}
    radius: ${md_corner_large}
    pad_all: ${md_space_large}

  # FAB Small
  button_fab_small: &button_fab_small
    <<: *button_fab
    radius: ${md_corner_medium}
    pad_all: ${md_space_medium}

  # FAB Large
  button_fab_large: &button_fab_large
    <<: *button_fab
    radius: ${md_corner_extra_large}
    pad_all: ${md_space_extra_large}

  # Disabled Button
  button_disabled: &button_disabled
    <<: *button_base
    bg_color: ${md_color_on_surface}
    text_color: ${md_color_surface}
    bg_opa: 12%
    text_opa: 38%

  # # Surface Styles
  # surface_styles: &surface_styles
  # Surface
  surface: &surface
    <<: *base_surface

  # Surface Dim
  surface_dim: &surface_dim
    <<: *base_surface
    bg_color: ${md_color_surface_dim}

  # Surface Bright
  surface_bright: &surface_bright
    <<: *base_surface
    bg_color: ${md_color_surface_bright}

  # Surface Container Lowest
  surface_container_lowest: &surface_container_lowest
    <<: *base_surface
    bg_color: ${md_color_surface_container_lowest}

  # Surface Container Low
  surface_container_low: &surface_container_low
    <<: *base_surface
    bg_color: ${md_color_surface_container_low}

  # Surface Container
  surface_container: &surface_container
    <<: *base_container

  # Surface Container High
  surface_container_high: &surface_container_high
    <<: *base_surface
    bg_color: ${md_color_surface_container_high}

  # Surface Container Highest
  surface_container_highest: &surface_container_highest
    <<: *base_surface
    bg_color: ${md_color_surface_container_highest}

  # Surface Variant
  surface_variant: &surface_variant
    <<: *base_surface
    bg_color: ${md_color_surface_variant}
    text_color: ${md_color_on_surface_variant}

  # # Card Styles
  # card_styles: &card_styles
  # Base Card
  card_base: &card_base
    <<: [*surface_container, *elevation_1]

  # Card Filled
  card_filled: &card_filled
    <<: *card_base
    bg_color: ${md_color_surface_container_highest}

  # Card Elevated
  card_elevated: &card_elevated
    <<: [*surface_container_low, *elevation_2]

  # Card Outlined
  card_outlined: &card_outlined
    <<: *surface_container_low
    border_width: 1
    border_color: ${md_color_outline_variant}

  # # Input Field Styles
  # input_styles: &input_styles
  # Base Input
  input_base: &input_base
    <<: *base_surface
    text_font: ${md_font_body_large}
    pad_all: ${md_space_large}

  # Filled Input
  input_filled: &input_filled
    <<: *input_base
    bg_color: ${md_color_surface_container_highest}
    radius: ${md_corner_extra_small}

  # Outlined Input
  input_outlined: &input_outlined
    <<: *input_base
    bg_color: ${md_color_surface}
    border_width: 1
    border_color: ${md_color_outline}
    radius: ${md_corner_extra_small}

  # # Typography Styles
  # typography_styles: &typography_styles
  # Display Typography
  display_large: &display_large
    text_font: ${md_font_display_large}
    text_color: ${md_color_on_surface}

  display_medium: &display_medium
    text_font: ${md_font_display_medium}
    text_color: ${md_color_on_surface}

  display_small: &display_small
    text_font: ${md_font_display_small}
    text_color: ${md_color_on_surface}

  # Headline Typography
  headline_large: &headline_large
    text_font: ${md_font_headline_large}
    text_color: ${md_color_on_surface}

  headline_medium: &headline_medium
    text_font: ${md_font_headline_medium}
    text_color: ${md_color_on_surface}

  headline_small: &headline_small
    text_font: ${md_font_headline_small}
    text_color: ${md_color_on_surface}

  # Title Typography
  title_large: &title_large
    text_font: ${md_font_title_large}
    text_color: ${md_color_on_surface}

  title_medium: &title_medium
    text_font: ${md_font_title_medium}
    text_color: ${md_color_on_surface}

  title_small: &title_small
    text_font: ${md_font_title_small}
    text_color: ${md_color_on_surface_variant}

  # Body Typography
  body_large: &body_large
    text_font: ${md_font_body_large}
    text_color: ${md_color_on_surface}

  body_medium: &body_medium
    text_font: ${md_font_body_medium}
    text_color: ${md_color_on_surface}

  body_small: &body_small
    text_font: ${md_font_body_small}
    text_color: ${md_color_on_surface_variant}

  # Label Typography
  label_large: &label_large
    text_font: ${md_font_label_large}
    text_color: ${md_color_on_surface}

  label_medium: &label_medium
    text_font: ${md_font_label_medium}
    text_color: ${md_color_on_surface}

  label_small: &label_small
    text_font: ${md_font_label_small}
    text_color: ${md_color_on_surface_variant}

  # # Layout Styles
  # layout_styles: &layout_styles
  # Flex Layout - Column
  flex_column: &flex_column
    layout:
      type: flex
      flex_flow: column
      flex_align_main: start
      flex_align_cross: stretch
      pad_row: ${md_space_small}

  # Flex Layout - Row
  flex_row: &flex_row
    layout:
      type: flex
      flex_flow: row
      flex_align_main: start
      flex_align_cross: center
      pad_column: ${md_space_small}

  # Grid Layout - 2 Column
  grid_2_column: &grid_2_column
    layout:
      type: grid
      grid_columns: [fr(1), fr(1)]
      grid_rows: [content]
      pad_column: ${md_space_medium}
      pad_row: ${md_space_medium}

  # Grid Layout - 3 Column
  grid_3_column: &grid_3_column
    layout:
      type: grid
      grid_columns: [fr(1), fr(1), fr(1)]
      grid_rows: [content]
      pad_column: ${md_space_small}
      pad_row: ${md_space_small}

  # ESPHome LVGL Style Definitions
  # These will be used in the actual LVGL configuration
  # Button Styles
  md_button_primary: |
    bg_color: ${md_color_primary}
    text_color: ${md_color_on_primary}
    radius: ${md_corner_large}
    pad_left: ${md_space_extra_large}
    pad_right: ${md_space_extra_large}
    pad_top: ${md_space_medium}
    pad_bottom: ${md_space_medium}
    text_font: ${md_font_label_large}
    align: center
    shadow_width: ${md_elevation_1_shadow_width}
    shadow_color: ${md_color_shadow}
    shadow_opa: ${md_elevation_1_shadow_opa}
    shadow_ofs_y: 1

  md_button_secondary: |
    bg_color: ${md_color_secondary_container}
    text_color: ${md_color_on_secondary_container}
    radius: ${md_corner_large}
    pad_left: ${md_space_extra_large}
    pad_right: ${md_space_extra_large}
    pad_top: ${md_space_medium}
    pad_bottom: ${md_space_medium}
    text_font: ${md_font_label_large}
    align: center
    shadow_width: ${md_elevation_1_shadow_width}
    shadow_color: ${md_color_shadow}
    shadow_opa: ${md_elevation_1_shadow_opa}
    shadow_ofs_y: 1

  md_button_outline: |
    bg_color: ${md_color_surface}
    text_color: ${md_color_primary}
    radius: ${md_corner_large}
    pad_left: ${md_space_extra_large}
    pad_right: ${md_space_extra_large}
    pad_top: ${md_space_medium}
    pad_bottom: ${md_space_medium}
    text_font: ${md_font_label_large}
    align: center
    border_width: 1
    border_color: ${md_color_outline}

  md_button_text: |
    bg_color: transparent
    text_color: ${md_color_primary}
    radius: ${md_corner_large}
    pad_left: ${md_space_extra_large}
    pad_right: ${md_space_extra_large}
    pad_top: ${md_space_medium}
    pad_bottom: ${md_space_medium}
    text_font: ${md_font_label_large}
    align: center

  md_button_fab: |
    bg_color: ${md_color_primary_container}
    text_color: ${md_color_on_primary_container}
    radius: ${md_corner_large}
    pad_all: ${md_space_large}
    text_font: ${md_font_label_large}
    align: center
    shadow_width: ${md_elevation_3_shadow_width}
    shadow_color: ${md_color_shadow}
    shadow_opa: ${md_elevation_3_shadow_opa}
    shadow_ofs_y: 4

  md_button_disabled: |
    bg_color: ${md_color_on_surface}
    text_color: ${md_color_surface}
    bg_opa: 12%
    text_opa: 38%
    radius: ${md_corner_large}
    pad_left: ${md_space_extra_large}
    pad_right: ${md_space_extra_large}
    pad_top: ${md_space_medium}
    pad_bottom: ${md_space_medium}
    text_font: ${md_font_label_large}
    align: center

  # Surface Styles
  md_surface: |
    bg_color: ${md_color_surface}
    text_color: ${md_color_on_surface}
    radius: ${md_corner_medium}
    pad_all: ${md_space_medium}

  md_surface_container: |
    bg_color: ${md_color_surface_container}
    text_color: ${md_color_on_surface}
    radius: ${md_corner_medium}
    pad_all: ${md_space_medium}

  # Card Styles
  md_card_filled: |
    bg_color: ${md_color_surface_container_highest}
    text_color: ${md_color_on_surface}
    radius: ${md_corner_medium}
    pad_all: ${md_space_medium}
    shadow_width: ${md_elevation_1_shadow_width}
    shadow_color: ${md_color_shadow}
    shadow_opa: ${md_elevation_1_shadow_opa}
    shadow_ofs_y: 1

  md_card_elevated: |
    bg_color: ${md_color_surface_container_low}
    text_color: ${md_color_on_surface}
    radius: ${md_corner_medium}
    pad_all: ${md_space_medium}
    shadow_width: ${md_elevation_2_shadow_width}
    shadow_color: ${md_color_shadow}
    shadow_opa: ${md_elevation_2_shadow_opa}
    shadow_ofs_y: 2

  md_card_outlined: |
    bg_color: ${md_color_surface_container_low}
    text_color: ${md_color_on_surface}
    radius: ${md_corner_medium}
    pad_all: ${md_space_medium}
    border_width: 1
    border_color: ${md_color_outline_variant}

  # Reusable Component Templates
  # These can be used with variables in ESPHome configurations

  # Button Component Template
  # Usage: !include_with_vars button_template.yaml { label: "Click Me", style: "${md_button_primary}" }
  button_template: &button_template
    - button:
          text: "${label}"
          styles: |
            ${style}
          on_press:
            then:
              - logger.log: "${label} pressed"

  # # Card Component Template
  # Usage: !include_with_vars card_template.yaml { title: "Card Title", content: "Card content", style: "${md_card_filled}" }
  card_template: &card_template
    - obj:
        styles: |
          ${style}
        widgets:
          - label:
              text: "${title}"
              styles: |
                text_font: ${md_font_title_medium}
                text_color: ${md_color_on_surface}
                align: top_left
          - label:
              text: "${content}"
              y: 24
              styles: |
                text_font: ${md_font_body_medium}
                text_color: ${md_color_on_surface_variant}
                align: top_left

  # Surface Component Template
  # Usage: !include_with_vars surface_template.yaml { style: "${md_surface_container}" }
  surface_template: &surface_template
    - obj:
        styles: |
          ${style}
        widgets: ${widgets}

  # Example Layout Templates
  app_bar_template: &app_bar_template
    - obj:
        height: 64
        width: 100%
        align: top_mid
        styles: |
          bg_color: ${md_color_surface_container}
          text_color: ${md_color_on_surface}
          pad_left: ${md_space_large}
          pad_right: ${md_space_large}
          pad_top: ${md_space_small}
          pad_bottom: ${md_space_small}
        layout:
          type: flex
          flex_flow: row
          flex_align_main: space_between
          flex_align_cross: center
        widgets:
          - label:
              text: "${title}"
              styles: |
                text_font: ${md_font_title_large}
                text_color: ${md_color_on_surface}
          - button:
              text: "${action_text}"
              styles: |
                ${md_button_text}

  bottom_nav_template: &bottom_nav_template
    - obj:
        height: 80
        width: 100%
        align: bottom_mid
        styles: |
          bg_color: ${md_color_surface_container}
          text_color: ${md_color_on_surface_variant}
        layout:
          type: flex
          flex_flow: row
          flex_align_main: space_evenly
          flex_align_cross: center
        widgets: ${nav_items}